#!/bin/sh

git add .

# Check for changes in the backend folder with specific file extensions
changed_files=$(git diff --cached --name-only | grep -E '^apps/backend/.*\.(js|ts|jsx|tsx)$')

if [ -n "$changed_files" ]; then
  echo "Detected changes in backend files. Running yarn build:backend..."
  yarn build:backend
  if [ $? -ne 0 ]; then
    echo "Build failed. Commit aborted."
    exit 1
  fi
else
  echo "No relevant changes detected. Skipping build."
fi